environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"

install:
  - choco install deluge --version=1.3.15
  - "%PYTHON%\\Scripts\\pip.exe install nose"

build: off

before_test:
  # For some reason we have to create the logfile first
  - ps: "New-Item -Path 'C:\\Users\\appveyor\\AppData\\Roaming\\deluge' -ItemType Directory"
  - ps: "Start-Process \"c:\\Program Files (x86)\\Deluge\\deluged.exe\""
  # Give deluged a chance to start
  - ps: "Start-Sleep -s 10"

test_script:
  - "%PYTHON%\\Scripts\\nosetests.exe"

on_failure:
  # Print the deluged log file to help debug problems
  - "type C:\\Users\\appveyor\\AppData\\Roaming\\deluge\\deluged.log"