environment:

  matrix:

    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
    # The list here is complete (excluding Python 2.6, which
    # isn't covered by this document) at the time of writing.

    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"

install:
  - choco install deluge --version=1.3.15
  - "%PYTHON%\\Scripts\\pip.exe install nose"

build: off

before_test:
  # For some reason we have to create the logfile first
  - ps: "New-Item -Path 'C:\\Users\\appveyor\\AppData\\Roaming\\deluge' -ItemType Directory"
  #- ps: "New-Item -Path 'C:\\Users\\appveyor\\AppData\\Roaming\\deluge\\deluged.log' -ItemType File"
  - "\"c:\\Program Files (x86)\\Deluge\\deluged.exe\" --do-not-daemonize"

test_script:
  - "%PYTHON%\\Scripts\\nosetests.exe"

on_finish:
  - "type C:\\Users\\appveyor\\AppData\\Roaming\\deluge\\deluged.log"